on:
  push:
    branches: 
      - main
  workflow_dispatch:
name: Update github pages branch on push
jobs:
  updateBranch:
    name: Update github pages
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: Embraser01/update-git-branch-action@v1.0.0
      if: github.ref == 'refs/heads/main'
      with:
        branch: gh-pages
        force: 1 # To push-force to the branch
        githubToken: ${{ secrets.GITHUB_TOKEN }}
