# Workflow from https://4comprehension.com/github-actions-reveal-js-and-automating-pdf-conversion/
# using Decktape https://github.com/astefanutti/decktape
# another option is https://github.com/bellbind/remarkjs-pdf
name: Create-PDF

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: 
      - main
    paths:
      - '*.html'
      
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    name: Generate PDF
    steps:
      - name: Create "/slides" directory
        run: mkdir presentation-pdfs && sudo chmod 777 presentation-pdfs
        
      - name:  Build pdfs   
        run:  
          docker run --rm -t -v `pwd`:/slides -v ~:/home/user astefanutti/decktape revealjs https://raw.githubusercontent.com/danielmarbach/PerformanceTricksAzureSDK/main/index.html slides/presentation.pdf -s 1920x1080
      
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./slides
          publish_branch: main
          keep_files: true
