name: Slides-Export
on:
  push:
    branches: 
      - main
    paths:
      - '*.html'
      
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    name: Generate PDF
    steps:
      - name: Git checkout
        uses: actions/checkout@v1

      - name: Create "/slides" directory
        run: mkdir slides && sudo chmod 777 slides
                
      - name: Build pdfs   
        run:  
          docker run --rm -t -v `pwd`:/ -v ~:/home/user astefanutti/decktape reveal index.html slides/presentation.pdf -s 1920x1080
      
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./slides
          publish_branch: main
          keep_files: true
