name: Slides-Export
on:
  push:
    branches: 
      - main
    paths:
      - '*.html'
      
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    name: Generate PDF
    steps:
      - name: Git checkout
        uses: actions/checkout@v1
        
      - run: npm install -g decktape
                
      - name: Build pdfs   
        run: decktape reveal index.html ./slides/presentation.pdf -s 1920x1080
      
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./slides
          destination_dir: ./slides
          publish_branch: main
          enable_jekyll: true
